export const dynamic = "force-dynamic";
import { revalidatePath } from "next/cache";
import { prisma } from "../lib/prisma";
import { auDate, inputDate, money } from "../lib/finance";
import { buttonClass, Card, inputClass, Panel, Shell } from "@/components/ui";
async function addSub(fd: FormData){"use server"; const name=String(fd.get("name")||"").trim(), date=String(fd.get("nextPaymentDate")||""); if(!name||!date)return; await prisma.subscription.create({data:{name,amount:Number(fd.get("amount")||0),frequency:String(fd.get("frequency")||"MONTHLY") as any,nextPaymentDate:new Date(date),active:String(fd.get("active")||"true")==="true"}}); revalidatePath("/subscriptions"); revalidatePath("/");}
async function deleteSub(fd: FormData){"use server"; const id=String(fd.get("id")||""); if(id) await prisma.subscription.delete({where:{id}}); revalidatePath("/subscriptions"); revalidatePath("/");}
async function toggleSub(fd: FormData){"use server"; const id=String(fd.get("id")||""); const active=String(fd.get("active"))==="true"; if(id) await prisma.subscription.update({where:{id},data:{active:!active}}); revalidatePath("/subscriptions"); revalidatePath("/");}
export default async function SubscriptionsPage(){const now=new Date(); const next7=new Date(now);next7.setDate(now.getDate()+7); const next30=new Date(now);next30.setDate(now.getDate()+30); const subs=await prisma.subscription.findMany({orderBy:{nextPaymentDate:"asc"}}); const active=subs.filter(s=>s.active); const due7=active.filter(s=>s.nextPaymentDate>=now&&s.nextPaymentDate<=next7); const due30=active.filter(s=>s.nextPaymentDate>=now&&s.nextPaymentDate<=next30); return <Shell title="Subscriptions" subtitle="Only future active payments are counted as upcoming."><section className="grid grid-cols-1 md:grid-cols-3 gap-5"><Card title="Monthly Burn" value={money(active.reduce((s,x)=>s+x.amount,0))}/><Card title="Next 7 Days" value={money(due7.reduce((s,x)=>s+x.amount,0))} tone="danger"/><Card title="Next 30 Days" value={money(due30.reduce((s,x)=>s+x.amount,0))} tone="warning"/></section><Panel title="Add Subscription"><form action={addSub} className="grid grid-cols-1 md:grid-cols-5 gap-3"><input name="name" placeholder="Name" className={inputClass}/><input name="amount" type="number" step="0.01" placeholder="Amount" className={inputClass}/><select name="frequency" className={inputClass}><option>WEEKLY</option><option>FORTNIGHTLY</option><option>MONTHLY</option><option>YEARLY</option></select><input name="nextPaymentDate" type="date" defaultValue={inputDate(now)} className={inputClass}/><button className={buttonClass}>Add</button></form></Panel><Panel title="All Subscriptions"><div className="space-y-3">{subs.map(s=><div key={s.id} className="flex justify-between items-center rounded-2xl bg-black/5 p-4"><div><p className="font-black">{s.name}</p><p className="text-sm text-black/50">{money(s.amount)} • {s.frequency} • next {auDate(s.nextPaymentDate)} • {s.active?"Active":"Inactive"}{s.nextPaymentDate<now?" • already paid/past":""}</p></div><div className="flex gap-2"><form action={toggleSub}><input type="hidden" name="id" value={s.id}/><input type="hidden" name="active" value={String(s.active)}/><button className="rounded-xl bg-black text-white px-4 py-2 font-bold">{s.active?"Pause":"Activate"}</button></form><form action={deleteSub}><input type="hidden" name="id" value={s.id}/><button className="rounded-xl bg-red-100 text-red-700 px-4 py-2 font-bold">Delete</button></form></div></div>)}</div></Panel></Shell>}
